version: "3.3"
services:
 
  tech-test:
    container_name: tech-test
    image: tech-test:latest
    ports:
      - "9292:9292"    
    restart: always
    links:
      - tech-test-db
  tech-test-db:
    container_name: tech-test-db
    image: postgres
    command: --init-file /data/application/init.sql
    volumes:
      - ./init.sql:/data/application/init.sql
    restart: always
    expose:
      - "5433"
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: tech-test
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres:/var/lib/postgresql/data

# to keep volume for starvo-dashboard alive
volumes:
  mongo_vol:
    external: true
networks:
  traefik-network:
    external: true
